development:
  adapter: postgresql
  database: myapp_development
  host: localhost
  port: 5432
  username: postgres
  password: password

test:
  adapter: postgresql
  database: myapp_test
  host: localhost